// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package automatedtesting.actions;

import automatedtesting.TestManager;
import automatedtesting.proxies.CoverageReport;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetCoverageReport extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __TestSuite;
	private automatedtesting.proxies.TestSuite TestSuite;

	public GetCoverageReport(IContext context, IMendixObject TestSuite)
	{
		super(context);
		this.__TestSuite = TestSuite;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.TestSuite = this.__TestSuite == null ? null : automatedtesting.proxies.TestSuite.initialize(getContext(), __TestSuite);

		// BEGIN USER CODE
		CoverageReport report = TestManager.instance().getCoverageReport(TestSuite, context());
		if (report != null) {
			return report.getMendixObject();
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetCoverageReport";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
