// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package automatedtesting.actions;

import com.mendix.core.Core;
import com.mendix.core.actionmanagement.CoreAction;
import com.mendix.core.actionmanagement.MicroflowCallBuilder;
import com.mendix.logging.LogSubscriber;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.core.actionmanagement.ActionCallBuilder;
import com.mendix.webui.CustomJavaAction;

public class JA_StartMicroflowListener extends CustomJavaAction<java.lang.Void>
{
	public JA_StartMicroflowListener(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		MicroflowCallBuilder builder = Core.microflowCall("AutomatedTesting.ACT_DoSomething");
		builder.execute(context());


		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_StartMicroflowListener";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
